baseurl = "https://example.org/"
languageCode = "en-us"
title = "Seth Hiegel's blog"
# Define how many pages appear per site
paginate = 10

# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command

[params]
    site_author = "Seth Hiegel"
    site_description = "Quick R tutorials"
    location = "Mercyhurst University"
    # Link custom assets relative to /static
    avatar = "img/profile.jpg"
    header_background = "img/ohiostate.jpg"
    header_title = "Quick R tutorials"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "seth_hiegel"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "shiege76"
    gplus     = ""
